### ISSUE TITLE
No response from SHT85

### ISSUE THREAD

**Issue by Taylor-Scion** [Sensirion/arduino-sht#33]
I have not been able to successfully connect to the SHT85 via I2C

SHT85 is wired up correctly with 3v3 VCC and 10k pull up resistors on sda and scl. 

When I run the auto detect example I get the following response:

init(): failed
Error in readSample()

I have also tried using the I2C_Scanner example to see if it was an address error but it finds nothing on the I2C bus. 

The example works fine for the SHT31 but not SHT85.  

Does the SHT85 have some strange requirements that make it incompatible with the standard Arduino wire library?

**Comment by winkj** [comment]
No, the SHT85 includes a standard SHT35 sensor, and shares the I2C interface with the other sensors in the SHT3x family, including the SHT31 that you tested. As such, no changes should be necessary to run the sensor.

Since the I2C_Scanner is failing to detect the sensor on the bus,  I would recommend to reach out to Sensirion's support via https://sensirion.com/forms/support-contact.
